### ISSUE TITLE
Allow passing a 'formatversion' parameter in Session constructor

### ISSUE THREAD

**Issue by yuvipanda** [mediawiki-utilities/python-mwapi#24]
To get back v2 formatted responses.

**Comment by halfak** [comment]
Thanks @yuvipanda.  Can you provide some more details about this v2 parameter or link to some docs?

**Comment by yuvipanda** [comment]
Paging @legoktm

**Comment by legoktm** [comment]
* https://www.mediawiki.org/wiki/API:JSON_version_2
* https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2015-May/000082.html

**Comment by halfak** [comment]
Oh.  My.  God.  working on this right now.
