### ISSUE TITLE
differant result struckture, mwapi vs mw-api-sandbox, ?

### ISSUE THREAD

**Issue by MvGulik** [mediawiki-utilities/python-mwapi#36]
Never really spotted, or realized this before. (_although there has been some nagging feeling about  mwapi's result output from time to time_)

When pulling some imageinfo data with the MW API-sandbox I got:
```
{ "query": { "pages": { "2601": { <imageinfo-datablock> }, ...  }  }  }
```

But when I use mwapi I get:
```
{ "query": { "pages": [ { <imageinfo-datablock> }, ...  ]  } }
```
The page-id and its containing dictionary are gone, replaced by a list containing the per-page imageinfo-datablock's

???
Should the output on both calls not be the same in structure ?
Is there any additional reading material on this ?

Os: Linux, ...
Python: 3.5.x
MWapi: 0.5.1
(MediaWiki: 1.31.0)

(_not checked against other mw-queries - yet_)
(_not re-checked mwapi docs - yet_)

**Comment by lucaswerkmeister** [comment]
The first output is the result of JSON format version 1, which is the default, whereas the second output is the result of JSON format version 2. You’re probably sending a `formatversion=2` parameter with your `mwapi` request, but didn’t set it in the API sandbox (it’s under the `format=json` “tab”).

**Comment by MvGulik** [comment]
Darn, formatversion never entered my mind. :-/

Your right, I was using different formatversions on the different calls.
Thanks. 

(Closing)
