### ISSUE TITLE
Default version updates ?

### ISSUE THREAD

**Issue by MvGulik** [mediawiki-utilities/python-mwapi#44]
The current default installed version is 0.5.1 (Dec 14, 2016)
 
Github master commits go up to 2019.

Any reasons why the default installed version is still at 0.5.1(_2016_) ?

\+
_Can I (relative) safely replace the 5-main-mwapi py files ?
(or would it not change anything in mwapi's functionalities ? (assuming there would be any py-code changes in the first place)_

**Comment by lucaswerkmeister** [comment]
I’d also very much like to see #38 in a released version :)

**Comment by lucaswerkmeister** [comment]
Apparently 0.6.0 and 0.6.1 were released last year and I didn’t notice? I should revisit my code that was waiting for #38 ^^

And I guess this task could be closed? (I don’t have the rights to do that, though.)
